2021-02-04 14:46:58,082 -  nornir.core -     INFO -        run() - Running task 'transform_nornir' with args {} on 1 hosts
2021-02-04 14:50:59,274 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'transform_nornir' failed with traceback:
Traceback (most recent call last):
  File "/home/bradfernan/VENV/py3_venv/lib64/python3.7/site-packages/nornir/core/task.py", line 85, in start
    r = self.task(self, **self.params)
  File "exercise2a.py", line 6, in transform_nornir
    import ipdb; ipdb.set_trace()
  File "/usr/lib64/python3.7/bdb.py", line 92, in trace_dispatch
    return self.dispatch_return(frame, arg)
  File "/usr/lib64/python3.7/bdb.py", line 154, in dispatch_return
    if self.quitting: raise BdbQuit
bdb.BdbQuit

2021-02-04 23:33:05,526 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show version'} on 10 hosts
2021-02-04 23:33:05,527 - nornir.core.task -    ERROR -      start() - Host 'localhost': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/home/bradfernan/VENV/py3_venv/lib64/python3.7/site-packages/nornir/core/task.py", line 85, in start
    r = self.task(self, **self.params)
  File "/home/bradfernan/VENV/py3_venv/lib64/python3.7/site-packages/nornir/plugins/tasks/networking/netmiko_send_command.py", line 26, in netmiko_send_command
    net_connect = task.host.get_connection("netmiko", task.nornir.config)
  File "/home/bradfernan/VENV/py3_venv/lib64/python3.7/site-packages/nornir/core/inventory.py", line 302, in get_connection
    extras=conn.extras,
  File "/home/bradfernan/VENV/py3_venv/lib64/python3.7/site-packages/nornir/core/inventory.py", line 352, in open_connection
    configuration=configuration,
  File "/home/bradfernan/VENV/py3_venv/lib64/python3.7/site-packages/nornir/plugins/connections/netmiko.py", line 58, in open
    self.connection = ConnectHandler(**parameters)
  File "/home/bradfernan/VENV/py3_venv/lib64/python3.7/site-packages/netmiko/ssh_dispatcher.py", line 287, in ConnectHandler
    device_type = kwargs["device_type"]
KeyError: 'device_type'

2021-02-04 23:33:41,651 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show version'} on 10 hosts
2021-02-04 23:33:41,652 - nornir.core.task -    ERROR -      start() - Host 'localhost': task 'netmiko_send_command' failed with traceback:
Traceback (most recent call last):
  File "/home/bradfernan/VENV/py3_venv/lib64/python3.7/site-packages/nornir/core/task.py", line 85, in start
    r = self.task(self, **self.params)
  File "/home/bradfernan/VENV/py3_venv/lib64/python3.7/site-packages/nornir/plugins/tasks/networking/netmiko_send_command.py", line 26, in netmiko_send_command
    net_connect = task.host.get_connection("netmiko", task.nornir.config)
  File "/home/bradfernan/VENV/py3_venv/lib64/python3.7/site-packages/nornir/core/inventory.py", line 302, in get_connection
    extras=conn.extras,
  File "/home/bradfernan/VENV/py3_venv/lib64/python3.7/site-packages/nornir/core/inventory.py", line 352, in open_connection
    configuration=configuration,
  File "/home/bradfernan/VENV/py3_venv/lib64/python3.7/site-packages/nornir/plugins/connections/netmiko.py", line 58, in open
    self.connection = ConnectHandler(**parameters)
  File "/home/bradfernan/VENV/py3_venv/lib64/python3.7/site-packages/netmiko/ssh_dispatcher.py", line 287, in ConnectHandler
    device_type = kwargs["device_type"]
KeyError: 'device_type'

2021-02-04 23:44:00,357 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show version'} on 9 hosts
2021-02-04 23:53:57,997 -  nornir.core -     INFO -        run() - Running task 'netmiko_send_command' with args {'command_string': 'show version'} on 9 hosts
